# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('relationship_to_wedding_party', models.CharField(max_length=200)),
                ('attending', models.NullBooleanField()),
                ('comments', models.TextField()),
                ('plus_ones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Meal'),
        ),
    ]
