# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
