# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_guest_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='guest',
            name='plus_ones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='relationship_to_wedding_party',
            field=models.CharField(default='', max_length=200),
        ),
    ]
