# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20170115_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wedding.Guest'),
            preserve_default=False,
        ),
    ]
