# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_guest_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedding.Guest'),
        ),
    ]
