# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_auto_20170115_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
